version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: camly-app
    volumes:
      - .:/app
      - .air.toml:/.air.toml
    working_dir: /app
    ports:
      - "8080:8080"
    networks:
      - golang_test_network
    depends_on:
      - db

  db:
    container_name: camly-db
    image: mysql:8.0
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - ./docker/db/.env_mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - golang_test_network

volumes:
  mysql_data:
    name: mysql_data

networks:
  golang_test_network:
    driver: bridge
