name: camly_app
description: Built for both iOS and Android platforms
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # packages
  camly_i18n:
    path: ../../packages/camly_i18n
  camly_lints:
    path: ../../packages/camly_lints
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.3.0
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.7
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/launcher_icon/
